### PR TITLE
Feature horizontal illusion line

### PR DESCRIPTION
**Pull request by Bamboudorer**

### CODE REVIEW

**Comment by grantjenks** [comment]
This is a great start! Few things:

1. Please change the function naming convention to use snake_case rather than camelCase
2. Would you add a screenshot? I’m curious how the illusion looks.
3. I’ve approved the check runs. Please address any failures.

**Comment by Bamboudorer** [comment]
Do I use the snake_case for the function and the variables ?

Here is the screenshot :
Screenshot 2022-04-05 214110

I will try my best to address the failures as soon as possible

**Comment by grantjenks** [comment]
That screenshot is great! Love it.

Yes, snake_case for both variable and function names.

**Comment by Bamboudorer** [comment]
I normally manage to fix the flake8 and the isortcheck.

I don't know how to review my code after the bluecheck. Is there a tool to help me to fix it ?

**Comment by grantjenks** [comment]
1. Install pipx (https://github.com/pypa/pipx)
2. Install tox like “pipx install tox”
3. Run “tox -e bluecheck” to see errors
4. Run “tox -e blue” to reformat the code

**Comment by Bamboudorer** [comment]
Thank you very much.

Normally, it would work.

I will do the same for the battleship game.

**Pull request merged**
